name: Benchmarking

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  MATURIN_VERSION: '1.9.4'
  RUST_TOOLCHAIN: nightly-2026-04-01
  PYTHON_VERSION: '3.12'

jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking with Bencher
    if: github.event_name == 'push'
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: DataTreehouse/maplib_benches
          path: maplib_benches
          ref: main
          ssh-key: ${{ secrets.BENCHES_DEPLOY_KEY }}
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Rust
        run: |
          rustup toolchain install ${{ env.RUST_TOOLCHAIN }}
          rustup default ${{ env.RUST_TOOLCHAIN }}

#      - uses: ./.github/actions/combine-sources

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install "maturin[patchelf]"==${{ env.MATURIN_VERSION }} pytest pytest-benchmark
          pip install -r maplib_benches/tests/requirements.txt

      - name: Build py_maplib
        run: |
          source .venv/bin/activate
          maturin develop --release -m py_maplib/Cargo.toml

      - uses: bencherdev/bencher@main

      - name: Track base branch benchmarks with Bencher
        run: |
          source .venv/bin/activate
          bencher run \
          --project maplib-bench-test \
          --key '${{ secrets.BENCHER_API_KEY }}' \
          --branch main \
          --testbed ubuntu-latest \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.99 \
          --thresholds-reset \
          --error-on-alert \
          --adapter python_pytest \
          --file results.json \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          "pytest --benchmark-only --benchmark-json results.json maplib_benches/tests/"