on:
  push:
    branches: main

jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking with Bencher
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: DataTreehouse/maplib_benches
          path: maplib-bench-test
          ref: main
          ssh-key: ${{ secrets.BENCHES_KEY }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: Swatinem/rust-cache@v2
      - name: Build py_maplib
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install maturin pytest pytest-benchmark
          maturin develop --release -m py_maplib/Cargo.toml
      - uses: bencherdev/bencher@main
      - name: Track base branch benchmarks with Bencher
        run: |
          source .venv/bin/activate
          bencher run \
          --project maplib-bench-test \
          --key '${{ secrets.BENCHER_API_KEY }}' \
          --branch main \
          --testbed ubuntu-latest \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.99 \
          --thresholds-reset \
          --error-on-alert \
          --adapter python_pytest \
          --file results.json \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          "pytest --benchmark-only --benchmark-json results.json maplib-bench-test"